name: CI-CD

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to docker.io
        run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master
      - name: Build image
        run: docker build . --file ./.ci/Dockerfile --tag ${{ secrets.DOCKER_LOGIN }}/${{ secrets.DOCKER_PROJECT }}:latest
      - name: Push image to docker.io
        run: docker push ${{ secrets.DOCKER_LOGIN }}/${{ secrets.DOCKER_PROJECT }}:latest
